# Generated by Django 3.2.3 on 2021-07-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20210706_1910'),
        ('userapp', '0006_auto_20210708_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='details1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='orders')),
                ('user', models.CharField(max_length=100)),
                ('proname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.register')),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
