# Generated by Django 3.2.3 on 2021-07-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20210711_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders1',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
